Add :remove-extra-whitespace? option
weavejester/cljfmt pull request #203
Opened 2020-08-21 09:55 UTC by mpenet

Hi James, 

This pr adds a `:remove-extra-whitespace?` (defaulting to false). 

This can be handy to turn a project that used justified form alignement into the classical form.

It will go through all whitespace nodes and replace the ones with more than 1 char with a single char whitespace node. 
I set the default to false has not to be too surprising since now cljfmt will deal both styles (justified or not) by not altering the result. It will leave comments untouched. 

One quirky thing is that it must/should be run with `:indentation? true` only, otherwise the source gets all "compressed", so there's an argument to make it an option for indentation? or maybe force indentation if that formatter is on, not sure about that one. 

```text
[a    b c] -> [a b c]
{:a    :b} -> {:a :b} 
```

2020-08-24 09:50 UTC, mpenet commented
> Can't you use this option to fix the spaces that are not part of the indentation, and use the indentation fixer to handle the indentation spaces?

Done as you suggested with latest commit.

2020-08-25 02:04 UTC, weavejester requested changes

2020-08-25 02:04 UTC, weavejester commented on cljfmt/src/cljfmt/core.cljc
> +(defn- non-indenting-spaces? [zloc]
This function could be written more succinctly as:

```clojure
(defn- non-indenting-space? [zloc]
  (and (whitespace? zloc) (not (indentation? zloc))))
```

Also we probably want to call it `non-indenting-whitespace?` come to think of it.

2020-08-25 02:04 UTC, weavejester commented on cljfmt/test/cljfmt/core_test.cljc
> +        "ensure comments are respected")
Remove "ensure " from description. "Testing comments are respected" works better than "Testing ensure comments are respected."

2020-08-25 02:04 UTC, weavejester commented on cljfmt/test/cljfmt/core_test.cljc
> +        "ensure custom indentation is respected")))
There should also be a test to ensure non-comment newlines work.

2020-08-26 07:51 UTC, mpenet commented
amended as per comments

2020-08-30 04:54 UTC, weavejester commented
Thanks! How is this option expected to work around forms with commas? For example: `{:a 1, :b 2}`.

2020-08-31 06:53 UTC, mpenet commented
> Thanks! How is this option expected to work around forms with commas? For example: `{:a 1, :b 2}`.

I think it should retain them. I added a test case to reflect this.

2020-09-02 07:16 UTC, mpenet commented
@weavejester let me know if you need any other changes to the PR. 

Something I was not sure about is making this a default or not, I guess it could be considered quite disruptive for people using "justified" alignment.

2020-09-02 14:31 UTC, weavejester commented
It shouldn't be the default, as the default should just just fix code that doesn't adhere to the Clojure style guide.

Can you change the commit message to:

```
Add :remove-multiple-non-indenting-spaces option

This option replaces all non-indenting horizontal whitespace with a
single space. Commas are preserved. This option is off by default.
```

2020-09-02 14:32 UTC, weavejester commented on cljfmt/src/cljfmt/core.cljc
> +  (and (whitespace? zloc)
Could you also put this on one line, so:

```clojure
(defn- non-indenting-whitespace? [zloc]
  (and (whitespace? zloc) (not (indentation? zloc))))
```

2020-09-02 14:38 UTC, mpenet commented
Done and squashed!

2020-09-02 14:48 UTC, merged

2020-09-02 14:48 UTC, weavejester commented
Merged. Thanks for the PR.

2020-09-02 14:49 UTC, mpenet commented
> Merged. Thanks for the PR.

Thanks!